services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel_requests_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - travel_network
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-travel_requests}
      - DB_USERNAME=${DB_USERNAME:-laravel_user}
      - DB_PASSWORD=${DB_PASSWORD:-laravel_password}
      - MAIL_MAILER=${MAIL_MAILER:-log}

  webserver:
    image: nginx:alpine
    container_name: travel_requests_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_PORT:-90}:90"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - travel_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: travel_requests_db
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT_EXTERNAL:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-travel_requests}
      MYSQL_USER: ${DB_USERNAME:-laravel_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel_password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root_password}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - travel_network

volumes:
  dbdata:
    driver: local

networks:
  travel_network:
    driver: bridge